-- Database schema for tg-welcome-bot

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT UNIQUE NOT NULL,
    username TEXT,
    first_name TEXT,
    last_name TEXT,
    source TEXT DEFAULT 'unknown',
    status TEXT DEFAULT 'approved',
    joined_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for querying by source (used in get_global_stats and get_user_stats)
CREATE INDEX IF NOT EXISTS idx_users_source ON users(source);

-- Index for joined_at (used for filtering today's joins)
CREATE INDEX IF NOT EXISTS idx_users_joined_at ON users(joined_at);
